apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    zone: default
    app: {{SERVICE_NAME}}
    version: "1.0"
  annotations:
    something: something
spec:
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        zone: default
        app: {{SERVICE_NAME}}
        version: "1.0"
        prometheus.io/scrape: 'true'
        qos-group: {{QOS_GROUP}}
        cosched.io/scheduler-name: {{SCHEDULER_IN_COSCHED}}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        qos-group: {{QOS_GROUP}}
        sidecar.istio.io/proxyMemory: "512Mi"        # memory request
        sidecar.istio.io/proxyMemoryLimit: "10Gi"    # memory limit
        sidecar.istio.io/proxyCPU: "500m"            # cpu request
        sidecar.istio.io/proxyCPULimit: "10000m"     # cpu limit
        sidecar.istio.io/userVolume: |
          [
            {"name":"schedsock", "hostPath": {"path":"/var/run/node-scheduler", "type": "DirectoryOrCreate"}},
            { "name":"registry-ca",
              "secret":{ "secretName":"registry-ca" }
            },
            {"name":"cosched-wasm","configMap":{"name":"cosched-wasm"}}
          ]
        sidecar.istio.io/userVolumeMount: |
          [
            {"name": "schedsock", "mountPath":"/var/run/node-scheduler", "readonly":false},
            { "name":"registry-ca",
              "mountPath":"/etc/registry-ca",
              "readonly": true
            },
            {"name":"cosched-wasm","mountPath":"/etc/istio/wasm","readonly":true}
          ]
        proxy.istio.io/config: |
          {"proxyMetadata":{"SSL_CERT_DIR":"/etc/ssl/certs:/etc/registry-ca"}}
    spec:
      terminationGracePeriodSeconds : 3
      schedulerName: {{SCHEDULER_NAME}}
      {{NODE_AFFINITY}}
      containers:
        - name: {{SERVICE_NAME}}
          image: {{IMAGE}}
          ports:
            - name: http-mubpodport
              containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - name: microservice-workmodel
              mountPath: /app/MSConfig
            - name: microservice-internal-services
              mountPath: /app/MSConfig/InternalServiceFunctions
            {{HOST_FILES_MOUNT_PATHS}}
          env:
            - name: APP
              value: {{SERVICE_NAME}}
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
            - name: K8S_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: PN
              value: {{PN}}
            - name: TN
              value: {{TN}}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LOGGER_LEVEL
              value: {{LOGGER_LEVEL}}

          resources: {{RESOURCES}}    
        
        {{SIDECAR}}

      {{POD_ANTIAFFINITY}}

      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: microservice-workmodel
          configMap:
            name: workmodel
        - name: microservice-internal-services
          configMap:
            name: internal-services
        {{HOST_FILES_VOLUMES}}